name: Update :help Search Index

on:
  # twice per month (4:35 at the 2nd and 15th of the month)
  schedule:
    - cron: "35 4 2,15 * *"

  # allow triggering manually
  workflow_dispatch: {}

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update :help Search Index
        run: |
          for i in {1..5}; do
            echo "Attempt #$i"
            zsh ./.github/help-index/create-index.sh && exit 0
            sleep 30
          done
          echo "Multiple attempts to update the index failed. Aborting."
          exit 1
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Updated :help index"
