name: Update :help Search Index

on:
  # twice per month (2:15 at the 2nd and 15th of the month)
  schedule:
    - cron: "15 2 2,15 * *"

  # allow triggering manually
  workflow_dispatch: {}

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update :help Search Index
        run: |
          zsh ./.github/help-index/create-index.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Updated :help index"
